name: Build and test

# Trigger the workflow when a workflow_dispatch is received.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 45

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set env variable BRANCH_FOR_SLACK for Slack message
        run: |
          if ${{ github.event_name == 'push' }} ; then
            echo "BRANCH_FOR_SLACK=${{ github.ref  }}" >> $GITHUB_ENV
          elif ${{ github.event_name == 'pull_request' }}; then
            echo "BRANCH_FOR_SLACK=${{ github.base_ref  }}" >> $GITHUB_ENV
          else
            exit 1
          fi
      
      - name: Run tests on MASTER branch
        if: ${{ github.base_ref == 'master' || github.ref == 'refs/heads/master' }}
        env: 
          FBN_TOKEN_URL: ${{ secrets.MASTER_FBN_TOKEN_URL }}
          FBN_USERNAME: ${{ secrets.MASTER_FBN_USERNAME }}
          FBN_PASSWORD: ${{ secrets.MASTER_FBN_PASSWORD }}
          FBN_CLIENT_ID: ${{ secrets.MASTER_FBN_CLIENT_ID }}
          FBN_CLIENT_SECRET: ${{ secrets.MASTER_FBN_CLIENT_SECRET }}
          FBN_LUSID_API_URL: ${{ secrets.MASTER_FBN_LUSID_API_URL }}
          FBN_APP_NAME: ${{ secrets.MASTER_FBN_CLIENT_ID }}
          FBN_ACCESS_TOKEN: ${{ secrets.MASTER_FBN_ACCESS_TOKEN }}
        run: | 
          echo "env variables for MASTER have been set"
          echo "Changing directory into examples directory"
          cd src          
          echo "Running the tests..."
          docker-compose up --abort-on-container-exit
          echo "Tests COMPLETED"

      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
            username: 'github-actions-tests',
            icon_emoji: ':octocat:',
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@PR-${{ github.event.inputs.pull_request }} by ${process.env.GITHUB_ACTOR} failed in ${process.env.AS_TOOK}`
            }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: failure()
